kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-marimo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marimo-app
  template:
    metadata:
      labels:
        app: marimo-app
    spec:
      containers:
        - name: my-marimo
          image: marimo-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-marimo
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: marimo-app
